# Generated by Django 3.1 on 2021-11-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_app', '0002_auto_20211107_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='facebook_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='likedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
