# Generated by Django 3.1 on 2021-11-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_date', models.DateTimeField(auto_now_add=True)),
                ('whats_on_mind', models.TextField(verbose_name='Write something about the blog ')),
                ('blog_sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sharer', to=settings.AUTH_USER_MODEL)),
                ('shared_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_blog', to='blog_app.blog')),
            ],
        ),
    ]
