# Generated by Django 3.1 on 2021-11-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0005_shared_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared_post',
            name='blog_sharer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_sharer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shared_post',
            name='shared_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_blog', to='blog_app.blog'),
        ),
    ]
