# Generated by Django 3.1 on 2021-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20211114_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_reference',
            field=models.URLField(null=True),
        ),
    ]
