# Generated by Django 3.1 on 2021-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_blog_blog_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(unique=True, verbose_name='What is on your mind?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(unique=True, upload_to='blog_images', verbose_name='Image'),
        ),
    ]
